version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=Transcription_Identity
      - Transcription_DB=Transcription_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
